CRITICAL - 2023-07-30 04:22:43 --> Undefined variable $rol_usuario
in APPPATH\Controllers\Dashboard.php on line 46.
 1 APPPATH\Controllers\Dashboard.php(46): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $rol_usuario', 'C:\\xampp\\htdocs\\proyectosistema\\app\\Controllers\\Dashboard.php', 46)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-07-30 04:22:43 --> Undefined variable $rol_usuario
in APPPATH\Controllers\Dashboard.php on line 46.
 1 APPPATH\Controllers\Dashboard.php(46): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $rol_usuario', 'C:\\xampp\\htdocs\\proyectosistema\\app\\Controllers\\Dashboard.php', 46)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-07-30 04:23:07 --> Undefined variable $rol_usuario
in APPPATH\Controllers\Dashboard.php on line 46.
 1 APPPATH\Controllers\Dashboard.php(46): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $rol_usuario', 'C:\\xampp\\htdocs\\proyectosistema\\app\\Controllers\\Dashboard.php', 46)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-07-30 04:23:08 --> Undefined variable $rol_usuario
in APPPATH\Controllers\Dashboard.php on line 46.
 1 APPPATH\Controllers\Dashboard.php(46): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $rol_usuario', 'C:\\xampp\\htdocs\\proyectosistema\\app\\Controllers\\Dashboard.php', 46)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dashboard->index()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dashboard))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-07-30 18:31:50 --> Undefined variable $num_transferencia
in APPPATH\Controllers\Pago.php on line 545.
 1 APPPATH\Controllers\Pago.php(545): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $num_transferencia', 'C:\\xampp\\htdocs\\proyectosistema\\app\\Controllers\\Pago.php', 545)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Pago->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pago))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-07-30 18:32:27 --> Undefined variable $num_transferencia
in APPPATH\Controllers\Pago.php on line 545.
 1 APPPATH\Controllers\Pago.php(545): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $num_transferencia', 'C:\\xampp\\htdocs\\proyectosistema\\app\\Controllers\\Pago.php', 545)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Pago->actualizar()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pago))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-07-30 23:33:05 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'dscriptn_root'@'localhost' (using password: YES) in C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'dscriptn_root', 'AkJkSzpj123', 'dscriptn_db_sis...', 3306, '', 0)
#1 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\proyectosistema\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\proyectosistema\system\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\proyectosistema\app\Models\Users.php(21): CodeIgniter\Model->__call('get', Array)
#6 C:\xampp\htdocs\proyectosistema\app\Controllers\Login.php(24): App\Models\Users->obtenerUsuario('admin123')
#7 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(934): App\Controllers\Login->acceder()
#8 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#9 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\proyectosistema\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\proyectosistema\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\proyectosistema\system\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\proyectosistema\app\Models\Users.php(21): CodeIgniter\Model->__call('get', Array)
#5 C:\xampp\htdocs\proyectosistema\app\Controllers\Login.php(24): App\Models\Users->obtenerUsuario('admin123')
#6 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(934): App\Controllers\Login->acceder()
#7 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\proyectosistema\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-07-30 23:33:05 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios`
WHERE `usuario` = :usuario:', [...], false)
 3 SYSTEMPATH\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Models\Users.php(21): CodeIgniter\Model->__call('get', [])
 5 APPPATH\Controllers\Login.php(24): App\Models\Users->obtenerUsuario('admin123')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Login->acceder()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-07-30 23:33:44 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'dscriptn_root'@'localhost' (using password: YES) in C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'dscriptn_root', 'AkJkSzpj123', 'dscriptn_db_sis...', 3306, '', 0)
#1 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\proyectosistema\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\proyectosistema\system\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\proyectosistema\app\Models\Users.php(21): CodeIgniter\Model->__call('get', Array)
#6 C:\xampp\htdocs\proyectosistema\app\Controllers\Login.php(24): App\Models\Users->obtenerUsuario('admin123')
#7 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(934): App\Controllers\Login->acceder()
#8 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#9 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\proyectosistema\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\proyectosistema\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\proyectosistema\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\proyectosistema\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\proyectosistema\system\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\proyectosistema\app\Models\Users.php(21): CodeIgniter\Model->__call('get', Array)
#5 C:\xampp\htdocs\proyectosistema\app\Controllers\Login.php(24): App\Models\Users->obtenerUsuario('admin123')
#6 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(934): App\Controllers\Login->acceder()
#7 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\xampp\htdocs\proyectosistema\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\proyectosistema\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-07-30 23:33:44 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios`
WHERE `usuario` = :usuario:', [...], false)
 3 SYSTEMPATH\Model.php(840): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Models\Users.php(21): CodeIgniter\Model->__call('get', [])
 5 APPPATH\Controllers\Login.php(24): App\Models\Users->obtenerUsuario('admin123')
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Login->acceder()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
